{% set version = "1.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fake
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fake_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fake/fake_{{ version }}.tar.gz
  sha256: dba09a360533c843eb1e24422e79ac52c71364de4d504ab76f7a79ee8b1205f1

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-rdpack
    - r-huge
    - r-igraph
    - r-withr >=2.4.0
  run:
    - r-base
    - r-mass
    - r-rdpack
    - r-huge
    - r-igraph
    - r-withr >=2.4.0

test:
  commands:
    - $R -e "library('fake')"           # [not win]
    - "\"%R%\" -e \"library('fake')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=fake
  license: GPL-3.0-or-later
  summary: This R package can be used to generate artificial data conditionally on pre-specified (simulated or user-defined) relationships between the variables and/or observations. Each observation is drawn from a multivariate Normal distribution where the mean vector and covariance matrix reflect the desired relationships.
    Outputs can be used to evaluate the performances of variable selection, graphical modelling, or clustering approaches by comparing the true and estimated structures (B Bodinier et al (2021) <arXiv:2106.02521>).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - barbarabodinier

# Package: fake
# Title: Flexible Data Simulation Using the Multivariate Normal Distribution
# Version: 1.3.0
# Date: 2022-12-08
# Author: Barbara Bodinier [aut, cre]
# Maintainer: Barbara Bodinier <b.bodinier@imperial.ac.uk>
# Description: This R package can be used to generate artificial data conditionally on pre-specified (simulated or user-defined) relationships between the variables and/or observations. Each observation is drawn from a multivariate Normal distribution where the mean vector and covariance matrix reflect the desired relationships. Outputs can be used to evaluate the performances of variable selection, graphical modelling, or clustering approaches by comparing the true and estimated structures (B Bodinier et al (2021) <arXiv:2106.02521>).
# License: GPL (>= 3)
# Language: en-GB
# Encoding: UTF-8
# RoxygenNote: 7.2.0
# Imports: huge, igraph, MASS, Rdpack, withr (>= 2.4.0)
# Suggests: testthat (>= 3.0.0),
# Config/testthat/edition: 3
# RdMacros: Rdpack
# NeedsCompilation: no
# Packaged: 2022-12-08 19:17:13 UTC; barbara
# Repository: CRAN
# Date/Publication: 2022-12-09 11:40:02 UTC
